In [2]:
import pandas as pd

In [3]:
df =pd.read_csv('banking.csv')

In [4]:
df

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,IND66827,Earl Hall,82,8760,09-10-2014,Joshua Bennett,American,Accounting Assistant III,High,Gold,...,1089957.03,532867.88,657849.62,12947.31,1238859.91,1,3,3,2,4
2996,IND40556,Billy Williamson,44,32837,05-02-2009,Dennis Ruiz,European,Paralegal,Mid,Gold,...,136891.32,56581.74,93195.61,23205.69,277171.07,1,2,3,2,5
2997,IND72414,Victor Black,70,36088,29-12-2009,Joshua Ryan,American,Statistician IV,Low,Jade,...,214860.89,158726.06,35539.15,30291.81,502947.22,2,2,3,2,6
2998,IND46652,Andrew Ford,56,24871,13-02-2006,Nicholas Cunningham,European,Human Resources Assistant III,Mid,Jade,...,742630.22,404638.26,56411.33,6413.14,1538368.60,3,1,3,2,7
2999,IND40216,Amy Nguyen,79,38518,08-12-2005,Joe Hanson,American,Biostatistician III,High,Jade,...,65617.66,77769.08,32371.38,8992.36,329412.55,1,1,3,2,8

In [5]:
df.shape

(3000, 25)

In [6]:
df.head()

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5

In [7]:
df.sample(50)

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
1909,IND16415,Edward Little,23,38166,01-03-2008,Jason Duncan,European,Payment Adjustment Coordinator,High,Gold,...,1127561.36,301741.77,260927.23,37286.16,626382.31,1,1,3,2,6
2604,IND44913,Stephanie Lopez,19,1516,02-12-2004,Ernest Rivera,European,Editor,Mid,Silver,...,153198.48,109427.49,45959.55,6098.49,1428173.95,2,2,1,1,21
2769,IND13675,Johnny Castillo,72,32245,23-02-2005,Dennis Ruiz,European,Senior Financial Analyst,Mid,Jade,...,259379.02,151518.44,52646.24,22486.23,381291.36,2,1,2,2,16
2214,IND14968,Ashley Powell,25,41662,08-01-2009,Douglas Tucker,Asian,Media Manager III,High,Jade,...,200786.44,74672.64,47458.61,25993.27,1580825.90,3,4,3,2,5
681,IND77117,Annie Lewis,19,40157,08-09-1996,Roger Alexander,European,Community Outreach Specialist,Mid,Jade,...,275056.64,168894.43,76726.32,8709.41,860302.06,3,1,1,1,2
1195,IND66679,Maria Larson,55,6710,28-01-1996,Shawn Long,American,Developer II,High,Silver,...,418230.27,253046.88,95454.91,29482.13,156066.83,3,1,3,1,6
2689,IND36692,Dorothy Kennedy,45,1346,14-03-2006,Dennis Morris,European,Teacher,High,Gold,...,219556.12,132335.20,117898.63,43711.49,611524.10,0,2,3,2,4
1477,IND46352,Michael Alexander,27,31923,09-09-2020,Frank Brown,Asian,Registered Nurse,Mid,Jade,...,673491.82,287293.71,145106.87,21362.94,713829.92,0,1,1,1,16
1871,IND59637,Nicholas Rice,30,33578,08-06-2008,Todd Roberts,American,Database Administrator I,Low,Jade,...,826697.10,273395.89,339792.04,6867.12,992277.02,1,1,3,2,2
566,IND56276,Lillian Moore,44,16197,26-10-2013,George Lewis,Asian,Accountant IV,Low,Gold,...,491522.76,419087.83,86508.01,51942.28,1249293.59,1,2,2,1,1
1729,IND79950,Paula Spencer,29,27002,21-05-2020,Joshua Bennett,American,Senior Cost Accountant,Mid,Jade,...,329466.05,287226.81,145978.80,23365.74,674003.53,0,3,4,2,11
827,IND29699,Roy Lee,45,24321,18-01-2006,Chris Armstrong,European,Statistician III,Low,Jade,...,1349926.19,714666.81,177872.63,2931.97,1464641.47,2,2,2,2,12
1576,IND35560,Harold Butler,60,4855,29-12-2021,Joe Hanson,European,Librarian,High,Jade,...,862135.02,197220.43,256386.56,13699.38,105736.40,3,1,3,1,13
2548,IND26959,Douglas Andrews,25,24495,30-03-2015,Jesse Evans,American,VP Quality Control,High,Jade,...,871947.70,444871.27,275820.19,47592.16,1323280.39,1,2,4,2,14
1438,IND93672,Steve Alvarez,73,8595,14-05-1995,Stephen Payne,Asian,Biostatistician II,High,Jade,...,1012079.53,319194.31,551194.09,20123.42,1369457.15,0,1,4,2,11
1641,IND84835,Margaret Grant,43,38087,16-01-2004,Phillip Peters,Asian,Statistician III,Mid,Silver,...,1146381.81,335526.38,668070.31,87161.11,439707.05,0,4,1,2,10
755,IND74286,Pamela Nichols,80,2474,07-08-2010,Bruce Butler,Asian,Project Manager,Low,Platinum,...,290695.76,349743.33,107602.85,21933.25,413073.87,0,3,2,1,8
2200,IND30193,Mary Bennett,28,17968,10-11-2012,Nicholas Cunningham,Asian,Accountant I,Low,Gold,...,449340.57,164758.21,217430.91,22500.29,628846.85,2,1,3,2,3
2846,IND22892,Marie Medina,29,38952,28-08-2020,Anthony Torres,European,Database Administrator I,High,Gold,...,33299.91,33820.23,10562.32,43534.26,905489.57,2,3,1,1,3
2158,IND52909,Amy Spencer,26,41251,28-12-2015,George Lewis,American,Database Administrator IV,High,Gold,...,110588.52,55294.26,127074.40,25602.89,503879.33,1,3,3,2,17
2005,IND81264,Thomas Hernandez,20,17844,02-06-2019,Anthony Simpson,European,Administrative Assistant II,Mid,Platinum,...,504109.24,216046.82,287822.37,15711.89,95000.43,3,1,3,2,15
2362,IND59891,Harold Oliver,42,9837,15-10-2010,Dennis Morris,European,GIS Technical Architect,Low,Jade,...,1932207.61,782986.09,436704.18,38257.62,853877.46,0,3,3,1,17
470,IND61034,Thomas Jenkins,46,9519,25-04-1995,Jeremy Vasquez,European,Account Representative III,Mid,Jade,...,1120446.35,330491.37,437538.33,62722.69,2502530.26,0,3,3,2,10
655,IND13248,Brenda Montgomery,63,31760,26-01-2010,James Castillo,European,Web Developer I,Mid,Jade,...,27280.61,13010.75,14479.71,8318.70,238537.00,3,1,4,1,10
1834,IND25277,Ruby Harper,75,30427,03-02-2020,Frank Brown,European,Senior Developer,Mid,Jade,...,52990.54,39198.48,20368.69,20930.06,205378.96,2,2,3,2,14
1764,IND76179,Joe Phillips,48,7564,13-02-2005,Roger Alexander,European,Biostatistician I,Low,Gold,...,334496.43,264601.66,246379.09,12214.80,619387.45,2,2,3,2,12
1910,IND39399,Mary Lynch,85,7625,02-12-2014,Paul Holmes,American,Social Worker,High,Jade,...,653231.97,210485.86,376189.03,35834.24,1171013.11,0,2,3,1,7
1238,IND63200,David Harris,51,25967,19-06-2006,Anthony Berry,European,Budget/Accounting Analyst I,High,Jade,...,239453.66,202039.03,44548.36,2968.42,214812.58,2,2,4,2,15
2099,IND42840,Kevin Diaz,19,36782,09-03-2005,Joshua Bennett,Asian,Clinical Specialist,Mid,Silver,...,669212.77,155430.06,210003.29,37652.45,408505.76,1,1,1,1,4
936,IND33792,Larry Young,36,6583,02-07-2018,Joshua Ryan,European,Social Worker,High,Gold,...,1743380.79,877872.60,243826.02,33724.38,686156.06,2,2,2,2,19
2209,IND91319,Bonnie Brown,82,27489,07-06-2009,Shawn Wallace,Asian,Dental Hygienist,Mid,Jade,...,150388.35,133201.11,96334.48,11288.13,408511.29,1,1,1,2,15
1776,IND90697,Juan Hughes,24,41486,30-12-1999,Bruce Porter,Asian,Sales Representative,Mid,Gold,...,774143.81,213019.44,358651.99,28162.15,1554596.09,2,2,3,2,9
1066,IND71984,Ruby Stewart,63,36182,16-11-1996,Patrick Graham,Asian,Senior Editor,Mid,Jade,...,453952.59,323363.49,301474.27,21003.07,697330.78,3,2,2,1,13
21,IND16101,Roger Boyd,58,12772,31-12-2015,Adam Hernandez,European,Web Designer II,High,Jade,...,547459.74,324420.58,42985.73,31481.78,1255331.52,3,2,3,2,22
1609,IND68824,Howard Patterson,52,25758,28-10-2010,Nicholas Simmons,African,General Manager,High,Gold,...,1407701.30,722873.64,223710.37,97886.22,3487314.08,1,5,1,1,12
399,IND52181,Nicholas Mitchell,73,13585,29-11-2016,George Lewis,Asian,Food Chemist,High,Jade,...,1051950.53,400198.57,624309.77,21641.11,1061775.40,1,5,4,2,4
1750,IND82408,Henry Chapman,35,2372,24-11-2014,Raymond Alexander,European,Research Assistant I,High,Gold,...,65615.31,68138.98,63848.75,6409.94,367943.19,3,1,2,1,17
782,IND80847,Brandon Tucker,63,14854,23-03-2020,Joshua Bennett,European,Geologist IV,High,Silver,...,127045.88,86132.80,23471.19,33808.99,708654.19,1,1,4,2,1
282,IND35821,Irene Barnes,36,13099,31-03-2014,Todd Roberts,European,Chief Design Engineer,High,Silver,...,207011.52,122426.17,70116.81,668.76,500477.87,3,2,2,1,11
1287,IND33629,Larry Pierce,50,9736,28-04-2020,Douglas Tucker,Asian,Software Test Engineer I,High,Jade,...,3252169.61,922601.31,941053.33,36986.53,2878551.34,3,5,3,1,11
993,IND30404,Samuel Peterson,73,31427,08-07-2011,Joshua Little,Asian,Web Developer II,High,Silver,...,917669.16,553300.52,78946.54,40142.79,1816702.88,3,2,3,2,8
1703,IND94590,Howard Hunt,37,33958,16-06-2011,Mark Montgomery,Asian,Biostatistician II,High,Jade,...,296880.20,134398.47,80097.48,55982.76,1788185.99,0,2,2,2,4
680,IND23452,Jose Evans,30,17677,10-10-2001,Joshua Little,American,Accountant I,High,Gold,...,455937.82,242882.76,108104.14,17093.79,127376.01,0,1,1,2,1
345,IND42135,Kevin Kelley,30,1037,04-05-2013,Victor Ramos,European,Environmental Tech,High,Jade,...,357419.79,137469.15,240571.01,3804.49,257335.65,0,2,4,2,6
1841,IND62657,Tammy Carter,76,28027,28-06-2005,Bruce Butler,Asian,Structural Analysis Engineer,Mid,Jade,...,451924.45,434762.76,127682.96,5367.88,923858.68,3,2,1,2,6
1051,IND70396,Ralph Harvey,82,18430,20-01-2010,Nicholas Cunningham,American,Project Manager,High,Jade,...,49515.35,39012.09,36011.16,25108.78,394976.37,3,2,3,2,13
1665,IND62564,Marie Hart,20,20106,30-10-1996,Keith Griffin,African,Recruiting Manager,Low,Jade,...,54859.24,25252.67,57497.71,35152.90,1162829.24,1,5,1,2,15
480,IND92942,Evelyn Murray,44,38658,11-06-2018,Jerry Green,European,Dental Hygienist,High,Jade,...,2031820.31,654884.23,1218924.27,683.47,570962.89,2,3,1,1,5
2490,IND40705,Charles Andrews,24,4579,17-01-1995,Shawn Wallace,European,Engineer I,Mid,Jade,...,544808.01,442656.51,176381.59,41004.89,771748.99,0,2,3,1,9
44,IND70083,Larry Green,56,12219,28-08-2016,Benjamin Kim,European,Human Resources Manager,Mid,Jade,...,208470.98,49811.65,134675.95,5026.45,407139.68,2,1,1,1,11

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Client ID                 3000 non-null   object
 1   Name                      3000 non-null   object
 2   Age                       3000 non-null   int64
 3   Location ID               3000 non-null   int64
 4   Joined Bank               3000 non-null   object
 5   Banking Contact           3000 non-null   object
 6   Nationality               3000 non-null   object
 7   Occupation                3000 non-null   object
 8   Fee Structure             3000 non-null   object
 9   Loyalty Classification    3000 non-null   object
 10  Estimated Income          3000 non-null   float64
 11  Superannuation Savings    3000 non-null   float64
 12  Amount of Credit Cards    3000 non-null   int64
 13  Credit Card Balance       3000 non-null   float64
 14  Bank Loans                3000 non-null   float64
 15  Bank Deposits             3000 non-null   float64
 16  Checking Accounts         3000 non-null   float64
 17  Saving Accounts           3000 non-null   float64
 18  Foreign Currency Account  3000 non-null   float64
 19  Business Lending          3000 non-null   float64
 20  Properties Owned          3000 non-null   int64
 21  Risk Weighting            3000 non-null   int64
 22  BRId                      3000 non-null   int64
 23  GenderId                  3000 non-null   int64
 24  IAId                      3000 non-null   int64
dtypes: float64(9), int64(8), object(8)
memory usage: 586.1+ KB

In [9]:
df.describe()

,Age,Location ID,Estimated Income,Superannuation Savings,Amount of Credit Cards,Credit Card Balance,Bank Loans,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3.000000e+03,3.000000e+03,3.000000e+03,3000.000000,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,51.039667,21563.323000,171305.034263,25531.599673,1.463667,3176.206943,5.913862e+05,6.715602e+05,3.210929e+05,2.329084e+05,29883.529993,8.667598e+05,1.518667,2.249333,2.559333,1.504000,10.425333
std,19.854760,12462.273017,111935.808209,16259.950770,0.676387,2497.094709,4.575570e+05,6.457169e+05,2.820796e+05,2.300078e+05,23109.924010,6.412303e+05,1.102145,1.131191,1.007713,0.500067,5.988242
min,17.000000,12.000000,15919.480000,1482.030000,1.000000,1.170000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,45.000000,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000
25%,34.000000,10803.500000,82906.595000,12513.775000,1.000000,1236.630000,2.396281e+05,2.044004e+05,1.199475e+05,7.479440e+04,11916.542500,3.748251e+05,1.000000,1.000000,2.000000,1.000000,5.000000
50%,51.000000,21129.500000,142313.480000,22357.355000,1.000000,2560.805000,4.797934e+05,4.633165e+05,2.428157e+05,1.640866e+05,24341.190000,7.113147e+05,2.000000,2.000000,3.000000,2.000000,10.000000
75%,69.000000,32054.500000,242290.305000,35464.740000,2.000000,4522.632500,8.258130e+05,9.427546e+05,4.348749e+05,3.155750e+05,41966.392500,1.185110e+06,2.000000,3.000000,3.000000,2.000000,15.000000
max,85.000000,43369.000000,522330.260000,75963.900000,3.000000,13991.990000,2.667557e+06,3.890598e+06,1.969923e+06,1.724118e+06,124704.870000,3.825962e+06,3.000000,5.000000,4.000000,2.000000,22.000000

In [10]:
df.columns

Index(['Client ID', 'Name', 'Age', 'Location ID', 'Joined Bank',
       'Banking Contact', 'Nationality', 'Occupation', 'Fee Structure',
       'Loyalty Classification', 'Estimated Income', 'Superannuation Savings',
       'Amount of Credit Cards', 'Credit Card Balance', 'Bank Loans',
       'Bank Deposits', 'Checking Accounts', 'Saving Accounts',
       'Foreign Currency Account', 'Business Lending', 'Properties Owned',
       'Risk Weighting', 'BRId', 'GenderId', 'IAId'],
      dtype='object')

In [13]:
df['Age'].value_counts()

Age
28    60
76    59
73    54
27    54
47    52
      ..
82    34
57    33
77    32
68    31
39    31
Name: count, Length: 69, dtype: int64

In [16]:
df['Estimated Income'].min()

np.float64(15919.48)

In [20]:
df['Nationality'].value_counts()

Nationality
European      1309
Asian          754
American       507
Australian     254
African        176
Name: count, dtype: int64

In [21]:
df['Fee Structure'].value_counts

<bound method IndexOpsMixin.value_counts of 0       High
1       High
2       High
3        Mid
4        Mid
        ...
2995    High
2996     Mid
2997     Low
2998     Mid
2999    High
Name: Fee Structure, Length: 3000, dtype: object>

In [23]:
df.isnull().sum()

Client ID                   0
Name                        0
Age                         0
Location ID                 0
Joined Bank                 0
Banking Contact             0
Nationality                 0
Occupation                  0
Fee Structure               0
Loyalty Classification      0
Estimated Income            0
Superannuation Savings      0
Amount of Credit Cards      0
Credit Card Balance         0
Bank Loans                  0
Bank Deposits               0
Checking Accounts           0
Saving Accounts             0
Foreign Currency Account    0
Business Lending            0
Properties Owned            0
Risk Weighting              0
BRId                        0
GenderId                    0
IAId                        0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [33]:
categorical_cols = [
    'BRId',
    'GenderId',
    'IAId',
    'Amount of Credit Cards',
    'Nationality',
    'Occupation',
    'Fee Structure',
    'Loyalty Classification'
]


for col in categorical_cols:
    print(f"value counts for'{col}:")
    display(df[col].value_counts())
    print("-"*40)

value counts for'BRId:

BRId
3    1352
1     660
2     495
4     493
Name: count, dtype: int64

----------------------------------------
value counts for'GenderId:

GenderId
2    1512
1    1488
Name: count, dtype: int64

----------------------------------------
value counts for'IAId:

IAId
1     177
2     177
3     177
4     177
8     177
9     176
13    176
12    176
10    176
11    176
14    176
15    176
6      89
5      89
7      89
16     88
17     88
18     88
19     88
20     88
21     88
22     88
Name: count, dtype: int64

----------------------------------------
value counts for'Amount of Credit Cards:

Amount of Credit Cards
1    1922
2     765
3     313
Name: count, dtype: int64

----------------------------------------
value counts for'Nationality:

Nationality
European      1309
Asian          754
American       507
Australian     254
African        176
Name: count, dtype: int64

----------------------------------------
value counts for'Occupation:

Occupation
Associate Professor             28
Structural Analysis Engineer    28
Recruiter                       25
Account Coordinator             24
Human Resources Manager         24
                                ..
Office Assistant IV              8
Automation Specialist I          7
Computer Systems Analyst I       6
Developer III                    5
Senior Sales Associate           4
Name: count, Length: 195, dtype: int64

----------------------------------------
value counts for'Fee Structure:

Fee Structure
High    1476
Mid      962
Low      562
Name: count, dtype: int64

----------------------------------------
value counts for'Loyalty Classification:

Loyalty Classification
Jade        1331
Silver       767
Gold         585
Platinum     317
Name: count, dtype: int64

----------------------------------------

In [27]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, explorative=True)
profile.to_file("output.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
  4%|███▎                                                                               | 1/25 [00:00<00:03,  6.93it/s]
  8%|██████▋                                                                            | 2/25 [00:00<00:04,  5.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 49.61it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]